# Generated by Django 2.1.5 on 2019-01-27 07:21
import json

from django.db import migrations

from ..models import Mineral


def save_minerals_to_db(apps, schema_editor):
    """Add minerals from the .JSON file to the database."""
    with open('minerals.json', encoding='utf-8') as mineral_file:
        data = json.load(mineral_file)

    for mineral in data:
        Mineral(
            name = mineral.get('name', ''),
            caption = mineral.get('image caption', ''),
            category = mineral.get('category', ''),
            group = mineral.get('group', ''),
            formula = mineral.get('formula', ''),
            strunz_classification = mineral.get('strunz classification', ''),
            crystal_system = mineral.get('crystal system', ''),
            mohs_scale_hardness = mineral.get('mohs scale hardness', ''),
            luster = mineral.get('luster', ''),
            color = mineral.get('color', ''),
            specific_gravity = mineral.get('specific gravity', ''),
            cleavage = mineral.get('cleavage', ''),
            diaphaneity = mineral.get('diaphaneity', ''),
            crystal_habit = mineral.get('crystal habit', ''),
            streak = mineral.get('streak', ''),
            optical_properties = mineral.get('optical properties', ''),
            refractive_index = mineral.get('refractive index', ''),
            unit_cell = mineral.get('unit cell', ''),
            crystal_symmetry = mineral.get('crystal symmetry', '')
        ).save()

class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(save_minerals_to_db)
    ]
